spring:
  application:
    name: quickstart-light
  datasource:
    # For H2
    url: jdbc:h2:./data_h2/mydb;AUTO_SERVER=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
    # For PostgreSQL
    # url: jdbc:postgresql://localhost:5432/your_database
    # username: your_username
    # password: your_password
    # driver-class-name: org.postgresql.Driver
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

server:
  port: 9201
  servlet:
    context-path: /${spring.application.name}

springdoc:
  show-actuator: true
  swagger-ui:
    path: /openapi-doc.html
logging:
  config: classpath:logback-spring.xml